### ISSUE TITLE
Stop working in production 

### ISSUE THREAD

**Issue by damienmasson** [unverbuggt/mkdocs-encryptcontent-plugin#40]
Hi, everything worked fine until I made a recent update of my website. It still work when testing with `mkdocs serve`, but does not work on generated site after a `mkdocs build`. 

Does not work means that the page keep continue to ask the password instead of decrypt the content.

I set up a very simple empty new project to expose the issue.
The result is here : http://igm.univ-mlv.fr/~masson/site/

The mkdocs.yml file: 
```
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: My Docs
theme:
  name: material

nav:
  - index.md
  - protected.md


plugins:
  - search: {}
  - encryptcontent: {}
```

and the content of the file protected.md:
```
---
password: pwd
---

this page is protected!
```

My mkdocs version:
`mkdocs, version 1.4.2 from /home/dm/.local/lib/python3.10/site-packages/mkdocs (Python 3.10)`

Any ideas ?
