### ISSUE TITLE
mkdocs returns 'Invalid Plugins configuration' when configuring mkdocs.yml

### ISSUE THREAD

**Issue by hylwxqwq** [unverbuggt/mkdocs-encryptcontent-plugin#42]
My mkdocs.yml was like this:
```yml
plugins:
  - search
  - encryptcontent:
    title_prefix: '[LOCKED]'
    password_button: True
```

I'm sure that I have installed the plugin, but when I try to test it locally, mkdocs said:

```powershell
C:\Users\Administrator\OIdocs>mkdocs serve
ERROR    -  Config value 'plugins': Invalid Plugins configuration
Aborted with 1 Configuration Errors!
```

But if I write like this:

```yml
plugins:
  - search
  - encryptcontent
```

Then the pages can be built, but there's no password request when I write like this in my markdown files:

```markdown
---
- password: CwoI2022
---

text.
```

It will be like this:

![QQ图片20230115201707](https://user-images.githubusercontent.com/77879721/212540108-f8d32138-98dc-4bba-a0b1-12346c3324c6.png)

full mkdocs.yml is [here(can be built)](https://pastebin.ubuntu.com/p/gDHSr3cY7V/) and [here(cannot be built)](https://pastebin.ubuntu.com/p/msT6mmS8Y9/)

Can anyone help me?

**Comment by hylwxqwq** [comment]
I've read the document of mkdocs, and change the mkdocs.yml to be like this:
```yml
plugins:
  search: {}
  encryptcontent:
    password_button: True
```

And change the metatag in markdown file like this:
```markdown
---
password: CwoI2022
---
```

I don't know why but it works!

![image](https://user-images.githubusercontent.com/77879721/212541848-2099a4cd-9f28-4225-b283-21d0429f81b9.png)
