### ISSUE TITLE
level: and !ENV not working, but local password: on a page is

### ISSUE THREAD

**Issue by guise** [unverbuggt/mkdocs-encryptcontent-plugin#51]
Hi — as per title 

I've stripped my project back to barebones trying to debug and figure out where I'm going wrong, but i've hit a brick wall. 

mkdocs.yml config: 

```yaml
site_name: Test
use_directory_urls: true
nav:
  - Test: test.md
plugins:    
  - search: {}
  - encryptcontent:
      password_inventory:
        secret1: 'test'
        secret2: !ENV TESTVAR
      password_button: true
```

test.md 

```markdown
---
level: secret1
---

# test heading

test page

```

Things are working fine using `password: test` as a meta tag in the test page, or setting a `global_password: 'test'` in mkdocs.yml 

However, setting `level: secret1` or `level: secret2` in test.md meta tags does nothing

`!ENV TESTVAR` also works fine when using it to set the page title. 

I feel like i'm going mad missing something obvious!?

I'm running: 

- python3 version `3.11.4`
- mkdocs version `1.5.2` from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mkdocs (Python 3.11)
- the latest release of mkdocs-encryptcontent-plugin (downloaded 1 sep 2023) - not sure how to check this
