### ISSUE TITLE
Dynamic search decryption in mkdocs-material

### ISSUE THREAD

**Issue by ttran2** [unverbuggt/mkdocs-encryptcontent-plugin#52]
I have set a `global_password` and used `encrypted_something` to hide the nav-bar (`md-nav`), tabs (`md-tabs`), and search-box (`md-search`). However, when providing the password and decrypting the page, only the nav-bar and tabs became visible, while the search-box was still hidden.

Here is a snippet from my `mkdocs.yml`
```yml
plugins:
  - search:
      indexing: 'full'
  - encryptcontent:
      search_index: 'clear'
      global_password: 'somepassword'
      encrypted_something:
        md-nav: [nav, class]
        md-tabs: [nav, class]
        md-search: [div, class]
```

PS. Yes, I am aware that setting the `search_index` to `clear` mode can make it possible to get the data by digging up the `search indexes`, however, downgrading the `mkdocs-material` to below `9.x.x` (and then patching it) is too big of a drawback, and disabling search feature is also a huge drawback.
