### ISSUE TITLE
Users re-prompted for password when navigating between pages

### ISSUE THREAD

**Issue by ElliotSknr** [unverbuggt/mkdocs-encryptcontent-plugin#61]
I have found that when navigating between different pages in my documentation with a global password enabled, that I am randomly being re-prompted for my password. A quick refresh of the page usually allows me in without having to retype the password in.

I am using a global password via the password_inventory with a list of passwords like so:

The behaviour occurs both when run via mkdocs serve, or when building and hosting in prod. Lastly I am using material for MkDocs, without any of the patches applied.
```yml
plugins:
    - encryptcontent:
        remember_password: True
        session_storage: True
        search_index: 'clear'
        inject:
            md-content: [div, class]
        encrypted_something:
            md-footer__inner: [nav, class] #Footer
            md-nav: [nav, class] #Menu and toc
            md-search: [div, class]
        title_prefix: ''
        password_inventory:
            _global:
                - password123
                - hunter2
```

When disabling the material theme, I no longer experience this behaviour, so it does seem to be associated with Material for MkDocs

**Comment by ElliotSknr** [comment]
![image](https://github.com/unverbuggt/mkdocs-encryptcontent-plugin/assets/16073141/34045ee7-0ebb-457d-9467-b42c5f7094ea)
I found that this log is printed out to the console when the issue occurs.

**Comment by unverbuggt** [comment]
Looks like it tries to use the CryptoJS, but it's not yet loaded. Normally this is circumvented with the "defer" attribute of "decrypt-content.js". 
We could try adding an additional safety net, by checking if CryptoJS is defined and recall the decryption a few milliseconds later and hope CryptJS is defined then...

Have you tried setting `webcrypto: true`? Using webcrypto might not cause such problems.

**Comment by unverbuggt** [comment]
One note on `md-search: [div, class]`: it was discussed in #52, that we currently found no way to show the search field only after decryption (for unpatched mkdocs-material with `search_index: 'clear'`) and we should not do so (as the search index contains the whole page unencrypted). 
So it's better to disable the search completely or set `search_index: 'encrypted'` to remove encrypted pages from the index.
But if you really want to do this maybe set a custom [block](https://squidfunk.github.io/mkdocs-material/customization/?h=override#overriding-blocks) in mkdocs-material where search is invisible by css attribute (and then use javascript to set it to visible after successful decryption).

Maybe this is related to the problem, but I couldn't reproduce said behavior (with neither crypto-js nor webcrypto). Maybe it is browser or cpu speed dependant. Or it is a bug in cryto-js, but crypto-js is pretty much dead, as all it's functionality is provided by the browser engines nowadays through webcrypto.

**Comment by ElliotSknr** [comment]
No luck unfortunately with setting `webcrypto: True`. The behaviour seems to have changed slightly as it now always displays the password screen whenever navigating between pages, requiring a refresh after every navigation.
The error message did change too after this modification

![Screenshot 2024-01-23 at 15 34 10](https://github.com/unverbuggt/mkdocs-encryptcontent-plugin/assets/16073141/e4617422-f4ad-41df-9250-81f00da0550f)

I've gone ahead and disabled search completely too following on from your prior comment, this didn't change the password re-prompting issue behaviour either unfortunately. I've got a few different machines I can test on so I'll see if that makes any difference with a minimal reproducible example project I'll setup, will update once I get the time.

**Comment by ElliotSknr** [comment]
Good news! I was able to track the issue down to a Material feature called `navigation.instant`
Removing this (as well as navigation.instant.progress) from my features block has resolved the issue.
```yml
theme:
    name: material
    features:
#        - navigation.instant
#        - navigation.instant.progress
```
For me the above change is fine as I don't require the instant loading feature.

Update: It looks like this has been discussed & fixed before https://github.com/unverbuggt/mkdocs-encryptcontent-plugin/issues/18
Potentially a regression occurred since?
