### ISSUE TITLE
Incrypt just one markdow file with password on ENV

### ISSUE THREAD

**Issue by alandrebraga** [unverbuggt/mkdocs-encryptcontent-plugin#64]
Hello! I'm new to this lib and i have this config on my files

plugins:
    - search: {}
    - encryptcontent:
        password_inventory:
            secret:
                user1: !ENV TESTE

Suposse that my user1 ENV TESTE password is test

How can i encrypt the file?

---
password: TESTE
---

I test with this metatag but dont work

**Comment by unverbuggt** [comment]
Hi,

the minimal mkdocs.yml is as follows:
```yaml
site_name: test

plugins:
  - search: {}
  - encryptcontent:
      password_inventory:
        secret:
          user1: !ENV TESTE
```

and you start your file_to_be_encrypted with the meta tag `level: secret` to refer to the level in the inventory, not `password:` (otherwise you'll set the password to "TESTE").

Before building or serving, you need to set the env variable to the password, otherwise the build will fail with "Empty password found for level 'secret' and user 'user1'!"
