### ISSUE TITLE
mkdocs-material & encrypted search: is it possible to leverage material's custom_dir to deploy your patched index.ts?

### ISSUE THREAD

**Issue by ryran** [unverbuggt/mkdocs-encryptcontent-plugin#66]
Hey there! I'm less than 12 hours into my journey of exploring mkdocs and mkdocs-material and this awesome plugin.

I read the documentation at [Search index encryption for mkdocs-material](https://unverbuggt.github.io/mkdocs-encryptcontent-plugin/features/search/#search-index-encryption-for-mkdocs-material). I'm doing this all via a GitLab pipeline, so I wasn't quite sure what to do until I read about material's support for [theme extension](https://squidfunk.github.io/mkdocs-material/customization/#setup-and-theme-structure) via the `custom_dir` option.

So here's what I did:
1. Downloaded [material_browser_request9_4p.patch](https://github.com/unverbuggt/mkdocs-encryptcontent-plugin/blob/version3/patches/material_browser_request9_4p.patch)
2. Downloaded [index.ts](https://github.com/squidfunk/mkdocs-material/blob/9.5.10/src/templates/assets/javascripts/browser/request/index.ts) from the latest material release and saved it to my git repo as `overrides/assets/javascripts/browser/request/index.ts`
3. Patched said file successfully
4. Updated my `mkdocs.yml` to include `custom_dir: overrides` under `theme`
5. Committed and pushed my changes to trigger the ci job that runs mkdocs

Oh PS: Here's my plugin config:
```yaml
plugins:
  - search
  - roamlinks
  - callouts
  - encryptcontent:
      webcrypto: true
      search_index: dynamically
      encrypted_something:
        md-nav: [nav, class]
        md-footer__inner: [nav, class]
      password_inventory:
        ...
```
Unfortunately, search still doesn't work for encrypted pages, even after decrypting.

Since I'm so brand-new to all of this, I couldn't help but ask: do you have any suggestions about what I might be doing wrong or what a better approach might be?
