### ISSUE TITLE
Can't make Environment Variables work

### ISSUE THREAD

**Issue by Momolem** [unverbuggt/mkdocs-encryptcontent-plugin#69]
Hey,

maybe I am just to incompetent but I cant make Environment Variables work and need some guidance:

My mkdocs section:
  ```yaml
    - encryptcontent:
      title_prefix: '🔐'
      password_inventory:
          secret: 
            user: !ENV VAULT
      summary: 'Private page'
      placeholder: 'Password'
      decryption_failure_message: 'Invalid password'
      encryption_info_message: "You don't have access to this page."
      search_index: 'encrypted'
      password_button: True
```

`echo $VAULT` displays "test"

But I still get the error:
`ERROR   -  Empty password found for level 'secret' and user 'user'!`

Can someone tell me what I am doing wrong :/
