### ISSUE TITLE
Move encrypted search entries to a separate file (besides seach_index.json)

### ISSUE THREAD

**Issue by GreggGreen** [unverbuggt/mkdocs-encryptcontent-plugin#74]
<img width="754" alt="Screenshot 2024-10-13 at 2 51 10 PM" src="https://github.com/user-attachments/assets/b3eaa839-b7c4-4be4-af21-0e659d253f5a">

**Comment by GreggGreen** [comment]
```
  - encryptcontent:
      title_prefix: ''
      password_file: 'pwd.yml'
      password_button: true
      password_button_text: continue
      hljs: False
      arithmatex: False
      mermaid2: False
      search_index: 'dynamically'

```
